In [0]:
import tensorflow as tf

In [0]:
x = tf.constant([2])
y = tf.constant([4])

z = tf.add(x,y)

In [16]:
with tf.Session() as sesssion:
  result = session.run(z)
  print(result)

[6]


In [20]:
Scalar = tf.constant([7])
Vector = tf.constant([5.2,6.1,2.8])
Matrix = tf.constant([[1,2,3],[9,8,7],[6,4,8]])
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf.Session() as session:
    result = session.run(Scalar)
    print(result)
    result = session.run(Vector)
    print(result)
    result = session.run(Matrix)
    print(result)
    result = session.run(Tensor)
    print(result)

[7]
[5.2 6.1 2.8]
[[1 2 3]
 [9 8 7]
 [6 4 8]]
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


In [25]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

first_operation = tf.add(Matrix_one, Matrix_two)
second_operation = Matrix_one + Matrix_two

with tf.Session() as session:
    result = session.run(first_operation)
    print("Defined using tensorflow function: ")
    print(result)
    result = session.run(second_operation)
    print("Defined using normal expressions: ")
    print(result)

Defined using tensorflow function: 
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Defined using normal expressions: 
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [27]:
Matrix_one = tf.constant([[2,3],[3,4]])
Matrix_two = tf.constant([[2,3],[3,4]])

first_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.Session() as session:
    result = session.run(first_operation)
    print("Defined using tensorflow function :")
    print(result)

Defined using tensorflow function :
[[13 18]
 [18 25]]


In [0]:
state = tf.Variable(0)

In [0]:
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

In [0]:
init_op = tf.global_variables_initializer()

In [33]:
with tf.Session() as session:
  session.run(init_op)
  print(session.run(state))
  for _ in range(3):
    session.run(update)
    print(session.run(state))

0
1
2
3


In [0]:
a=tf.placeholder(tf.float32)

In [0]:
b=a**2

In [40]:
with tf.Session() as sess:
    result = sess.run(b,feed_dict={a:5})
    print(result)

25.0


In [42]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print(result)

[[[  1.   4.   9.]
  [ 16.  25.  36.]
  [ 49.  64.  81.]
  [100. 121. 144.]]

 [[169. 196. 225.]
  [256. 289. 324.]
  [361. 400. 441.]
  [484. 529. 576.]]]


In [43]:
a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a,b)
d = tf.subtract(a,b)

with tf.Session() as session:
    result = session.run(c)
    print(result)
    result = session.run(d)
    print(result)

[7]
[3]
